document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"pt-BR\">");
document.writeln("<head>");
document.writeln("  <meta charset=\"UTF-8\">");
document.writeln("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("  <title>Portfolio - André Ribas</title>");
document.writeln("  <link rel=\"shortcut icon\" href=\"person-outline.svg\"> ");
document.writeln("  <meta name=\"author\" content=\"André Ribas\">");
document.writeln("  <meta name=\"description\" content=\"Portfolio de André Ribas\">");
document.writeln("  <meta name=\"keywords\" content=\"portfolio, portifolio, andré, ribas\">");
document.writeln("  <meta name=\"copyright\" content=\"© 2021 André Ribas\" />");
document.writeln("  <meta name=\"robots\" content=\"index,follow\">");
document.writeln("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css\"/>");
document.writeln("  <link rel=\"stylesheet\" href=\"style.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("  <div class=\"profile-card\">");
document.writeln("    <div class=\"card-header\">");
document.writeln("      <div class=\"pic\">");
document.writeln("        <img src=\"/photo-profile.jpg\" alt=\"\">");
document.writeln("      </div>");
document.writeln("      <div class=\"name\">André Ribas</div>");
document.writeln("      <div class=\"desc\">Telegram Bot Developer, Web Developer, CEO & Founder of ARNext Robot</div>");
document.writeln("      <div class=\"sm\">");
document.writeln("        <a href=\"https://t.me/andre_ribas1\" class=\"fab fa-telegram\"></a>");
document.writeln("        <a href=\"https://twitter.com/andre_ribas1\" class=\"fab fa-twitter\"></a>");
document.writeln("        <a href=\"https://github.com/andreribas15\" class=\"fab fa-github\"></a>");
document.writeln("        <a href=\"https://new.andreribas.arnext.xyz\" class=\"fas fa-globe\"></a>");
document.writeln("      </div>");
document.writeln("      <a href=\"https://new.andreribas.arnext.xyz/contact\" class=\"contact-btn\">Contact Me</a>");
document.writeln("    </div>");
document.writeln("    <div class=\"card-footer\">");
document.writeln("      <div class=\"numbers\">");
document.writeln("        <div class=\"item\">");
document.writeln("          <span>12</span>");
document.writeln("          Posts");
document.writeln("        </div>");
document.writeln("        <div class=\"border\"></div>");
document.writeln("        <div class=\"item\">");
document.writeln("          <span>284</span>");
document.writeln("          Following");
document.writeln("        </div>");
document.writeln("        <div class=\"border\"></div>");
document.writeln("        <div class=\"item\">");
document.writeln("          <span>291</span>");
document.writeln("          Followers");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("  <audio autoplay=\"autoplay\"><source src=\"https://drive.google.com/file/d/1YOWuLEWRYhzTBeND0bQ5OW5Es7L0dXvV/view?usp=drivesdk\" type=\"audio/mp3\" /></audio>");
document.writeln("<script type=\"module\" src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>");
document.writeln("<script nomodule src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js\"></script></body>");
document.writeln("</html>");
